### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shreyaspapi** [anshuman73/bennett-lms-downloader#3]
The program is only creating empty directories of all the courses.

**Comment by shreyaspapi** [comment]
You should handle these issues fast and reply with at least a confirmation that you have seen it.

**Comment by arjunmohnot** [comment]
![Screenshot (74)](https://user-images.githubusercontent.com/33459977/55624952-0a084a00-57c5-11e9-9a33-6419f8bfb507.png)
![Screenshot (75)](https://user-images.githubusercontent.com/33459977/55624953-0aa0e080-57c5-11e9-8fce-e80f0118f571.png)

@shreyaspapi  See I can download :)

**Comment by shreyaspapi** [comment]
There might be some issues with the specific OS, I used macOS to test it.

**Comment by anshuman73** [comment]
@shreyaspapi are you getting a stack track / log ?
have you messed with maybe adding a print statement here and there for debugging basis ?
